---
version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis_queue
    restart: always
    ports:
      - '6379:6379'
#    environment:
#      - REDIS_PASSWORD=secret
    volumes:
      - ./data:/data

volumes:
    data-volume:

